feat: initial implementation for code editor toolbar
The-Programming-Foundation/tutorials pull request #17
Opened 2020-12-14 21:58 UTC by yu-emily

Based on issue #13 [Implementation: Finalize Code Editor Toolbar](https://github.com/The-Programming-Foundation/tutorials/issues/13)
Build responsive toolbar with buttons and fields based on this [UI design](https://user-images.githubusercontent.com/49451794/102140127-ae081c80-3e13-11eb-8940-65f061d94f86.png). Functionalities not yet completely implemented.

Libraries used:
bootstrap, [react-bootstrap](https://react-bootstrap.github.io/), [gatsby-plugin-google-fonts](https://www.gatsbyjs.com/plugins/gatsby-plugin-google-fonts/), [react-icons](https://react-icons.github.io/react-icons)

2020-12-14 22:04 UTC, yu-emily commented
Currently, only the theme changes when you click on the sun/moon icon.
The demo can be viewed in Programming > Python > Hello Earth.
(Component currently uses useState. Will update to useRef when implementing datastore for editor.)

2020-12-16 15:01 UTC, ReesMcD commented
There is a ticket to research CSS Libraries and Frameworks to use, so that we can unify around one package (maybe two if needed) so we might end up refactoring from the bootstrap solutions you implemented but I think as of right now it's good.

2020-12-16 15:04 UTC, ReesMcD approved these changes

2021-01-17 16:38 UTC, ashwinkjoseph requested changes
Can we make use of styled-components rather than native styling?

Also, can you add some method of obtaining the code from the editor?

2021-01-17 16:38 UTC, ashwinkjoseph commented on src/components/EditorToolbar.jsx
> +    const buttonStyle = {
I see that we are using the native react styling and using it directly on HTML Elements. Didn't we agree on either using individual SCSS files or using Styled components?

Could you look into moving this into Styled components?

2021-03-21 14:28 UTC, closed without merging