New branch
The-Programming-Foundation/tutorials pull request #37
Opened 2021-06-08 14:54 UTC by eelay234

2021-06-09 12:41 UTC, bootkernel requested changes
@eelay234 Great contributions dividing the Expansion to dedicated better sections. :100: 

Couple of important things:

1. Might be better to change the directory names by removing the spaces "file handling" -> "file-handling" and "conditional statements" -> "conditional-statements" 
2. Since the directory structure is changing, the https://github.com/The-Programming-Foundation/tutorials/blob/master/src/data/LessonTopic.json needs to be updated by replacing the Expansion and sequentially adding the sections updating them with titles, subtitles and images from [https://unsplash.com/](https://unsplash.com/) feel free to chose any image you think is suitable. PS make sure to change the ids of the following snippets otherwise it will break.
3. Sequencing them as Conditional Statements ->  Loops -> Functions -> File Handling is suggested but if you think that swapping File Handling with Functions makes more sense, feel free to sequence them that way in the json file, up to you.
4. To add the Python Interactive Shell on the right panel, add <CodeLabLayout title="Nameofpage"> after mdx page title and at the end of the mdx file. Here's an example: https://raw.githubusercontent.com/The-Programming-Foundation/tutorials/master/lessons/programming/python/hello-earth/index.mdx
5. This branch doesn't seem to be in sync with the master branch, will cause merge conflict, might be better to do a pull.

Otherwise, we're all set. :+1:

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/conditional statements/index.mdx
> +## 1. if statement:
**if statement** -> **If Statement**

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/conditional statements/index.mdx
> +not true thus does nothing.
_Since a condition can have multiple parameters, it might be better to avoid "one condition"_

~~It has one condition and~~ -> If a condition is true, it'll take action; otherwise, it'll do nothing.

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/conditional statements/index.mdx
> +For example,
~~For example,~~ -> **For example:**

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/conditional statements/index.mdx
> +     output "You won!"
Use ```
```
if a number is equal to the pre-set number:
     output "You won!"
```

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/conditional statements/index.mdx
> +```
add **Python** after ```

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/conditional statements/index.mdx
> +#### Python syntax:
"###"

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/conditional statements/index.mdx
> +Output:
In bold

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/conditional statements/index.mdx
> +    print("You won!")
Might be better to add comments:

_Assigning a number to the winning_number variable
Assigning the user int input to the num variable or Asking the user to type in a lucky integer number_

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/conditional statements/index.mdx
> +## 2. if-else statement:
if-else statement: -> **If-Else Statement**

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/conditional statements/index.mdx
> +It takes one action when the condition is true and another action when the condition is false.
~~It takes one action when the condition is true and another action when the condition is false.~~ -> **You can assign it to perform an action if a condition is true and a different action when the condition is false; therefore, different actions can be processed based on the condition.**

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/conditional statements/index.mdx
> +For example, a math tutor tells if the answer to a math question is correct or not and displays the correct answer if the answer is incorrect.
For example, a math tutor ~~tells~~ -> **evaluates**

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/conditional statements/index.mdx
> +```
add **Python** after ```

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/conditional statements/index.mdx
> +if answer == 2**8:
Might be better to add comments:

** means exponents - number ** [exponent value]

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/conditional statements/index.mdx
> +Output:
In **bold**

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/conditional statements/index.mdx
> +## 3. if-elif-else statement:
~~if-elif-else~~ statement: -> **If-Elif-Else Statements:**

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/conditional statements/index.mdx
> +it has more than one condition, and it takes different actions depending on the condition. If all conditions do not match, it does the action of the "else" part.
~~it~~ has -> **I**t has

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/conditional statements/index.mdx
> +For example, know the letter grade 'A', 'B', 'C', 'D', or 'F' by the score.
For example, ~~know~~ the letter grade 'A', 'B', 'C', 'D', or 'F' ~~by the score.~~ -> For example, to **find** the letter grade ('A', 'B', 'C', 'D', or 'F') **based on the following chart:**

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/conditional statements/index.mdx
> +
_Add:_

We can use the following syntax:

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/conditional statements/index.mdx
> +)
Add this as a **Note: ** after ``` and before Python Implementation in line 94.

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/conditional statements/index.mdx
> +
Add line 88-89 here as a Note:

**Note:** There can more than one elif condition.

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/conditional statements/index.mdx
> +Output:
In **bold**

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/conditional statements/index.mdx
> +## 4. Python shorthand if-else:
_Might be better to add a short description like:_

The above code can be written using fewer lines.

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/conditional statements/index.mdx
> +action1 if condition else action2
Add ```

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/conditional statements/index.mdx
> +Output:
In **bold**

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/file handling/index.mdx
> +To perform a file operation, first,  a file has to be opened. Then the file operation is performed. Close the file afterward.
first,  a file -> first, [remove extra space] a file has to be opened. Then the file operation ~~is~~ -> **can be** performed ~~. Close~~ -> and closed afterwards.

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/file handling/index.mdx
> +The built-in open() function opens a file. It accesses a file by the specified filename (in the current directory) or a path to that file.
open() in bold  ->**open()**

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/file handling/index.mdx
> +'x': Creates the specified file. An error occurs if the file exists.
Might be better to reorganize it from:

r a w x -> r w a x

and styling them like **bold letter:** description.

**'r':** Opens the specified file for reading, and this is the default mode of operation. An error occurs if a file does not exist.

and so on....

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/file handling/index.mdx
> +```
styling them like the following instead of using ```:

**t:** Text mode, and this is the default mode.

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/file handling/index.mdx
> +```
Same here too, avoid ``` and use bold for the () names.

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/file handling/index.mdx
> +```
Same here too, avoid ``` and use **bold** for the () names.

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/file handling/index.mdx
> +Python function close() will free up the memory spaces used by the file.
Add **The** before Python and **close()** in bold.

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/file handling/index.mdx
> +It is first opened by open(), then one line is read in and counted at a time; after all lines are read in and counted, the file is closed, and the number of lines is displayed.
It is first opened by ~~open()~~ -> **open(),** then ~~one~~ -> each line is read ~~in~~ and counted at a time; after all lines are read ~~in~~ and counted, the file is closed, and the number of lines is displayed.

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/file handling/index.mdx
> +records = open("records.txt", "r")
Might be better to add a comment:

_opens records.txt in the current directory with read mode_

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/file handling/index.mdx
> +records.close()
Might be better to add a comment:

_closes records.txt with close()_

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/file handling/index.mdx
> +num_records = 0
Might be better to add a comment:

_the num_records variable acts as a counter and therefore, is initially set to 0_

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/file handling/index.mdx
> +#### Output:
#### Output -> **Output:** in bold

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/file handling/index.mdx
> +"With" statement prevents the problem that the file is not closed properly.
~~W~~ith -> **"with"** statement prevents ~~problem~~ -> **errors** if the file is not closed properly.

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/file handling/index.mdx
> +with open("shopping_memo.txt", "w") as f:
Might be better to comment what **as f** is doing

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/file handling/index.mdx
> +with open("shopping_memo.txt", "r") as f:
Might be better to comment what **as f** is doing

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/file handling/index.mdx
> +#### Output:
####Output -> **Output** in bold

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/functions/index.mdx
> +Functions are known as building blocks of programs. A large problem can be divided into smaller functions, achieving modularity, reusability, and readability.
Functions are known as **the** building blocks of programs. A large problem can be divided into smaller functions, achieving modularity, ~~reusability~~ -> re-usability, and readability.

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/functions/index.mdx
> +- Essentially speaking, a function accepts some inputs, performs computations, and outputs the results.
No need ~~Essentially speaking,~~

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/functions/index.mdx
> +Built-in functions are pre-defined in and a part of Python languagne. For example, print(), range(), and type().
pre-defined ~~in~~ and ~~a~~ part of the Python ~~languagne~~ -> **language**~~. For example,~~ -> such as print(), range(), and type().

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/functions/index.mdx
> +User-defined functions are defined by users. To define a Python function, begin with keyword **def** and follow by a function name.
**def** ~~and follow~~ -> followed by a function name.

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/functions/index.mdx
> +### To define a Python function with no argument and no return value:
~~To define a~~ -> **A** Python function with no argument and ~~no~~ return value:

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/functions/index.mdx
> +### A Python function with arguments and return value
_Add :_
return value -> return value:

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/functions/index.mdx
> +op = input("Enter operator: ")
("Enter two numbers: ") -> ("Enter two numbers (x, y): ")

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/loops/index.mdx
> +- **Break statement** - Break out of the loop by using a break keyword; This caused the execution to move out of the loop and executes the next statement following the loop code.
using a break -> **break**  keyword; this ~~caused~~ -> **causes** the ~~execution~~ -> **process** to move out of the loop and execute~~s~~ -> **execute** the next statement following the loop code.

2021-06-09 12:41 UTC, bootkernel commented on lessons/programming/python/loops/index.mdx
> +print("Found") if found else print("not found")
print("~~n~~ot found") -> print("**N**ot found")

2021-06-11 22:29 UTC, eelay234 commented
Hi Subhajeet,

Thank you for the review.

>Might be better to change the directory names by removing the spaces "file
handling" -> "file-handling" and "conditional statements" ->
"conditional-statements"
Done.

>Since the directory structure is changing, the
https://github.com/The-Programming-Foundation/tutorials/blob/master/src/data/LessonTopic.json
needs to be updated by replacing the Expansion and sequentially adding the
sections updating them with titles, subtitles and images from
https://unsplash.com/ feel free to chose any image you think is suitable.
PS make sure to change the ids of the following snippets otherwise it will
break.
The titles and subtitles of the four new titles in LessonTopic.json have
been updated. For image values, I just put the image names I picked from
unsplash.com (attached please fine the four images) in the dictionary
structure, thus they have to be changed after images are uploaded to your
web site.
image for conditional-statement:
alexander-schimmeck-Aohf8gqa7Zc-unsplash.jpg
image for loops: nareeta-martin-za2gMSfLmzU-unsplash.jpg
image for functions: nathan-dumlao-fEKMMV0LF2o-unsplash.jpg
image for file-handling: viktor-talashuk-05HLFQu8bFw-unsplash.jpg

LessonTopic.json was attached with the image files, however it was not
committed neither pushed yet.

>Sequencing them as Conditional Statements -> Loops -> Functions -> File
Handling is suggested but if you think that swapping File Handling with
Functions makes more sense, feel free to sequence them that way in the json
file, up to you.
Done. Yes, the sequnece of Conditional Statements -> Loops -> Functions ->
File Handling is the proper one for two reasons:
1. Build-in functions are used for file handling operations
2. Usually when no files need to be processed, file handling operataions
are not used.

>To add the Python Interactive Shell on the right panel, add after mdx page
title and at the end of the mdx file. Here's an example:
https://raw.githubusercontent.com/The-Programming-Foundation/tutorials/master/lessons/programming/python/hello-earth/index.mdx
Done. Later maybe we can add an editor and run-code functionalities.

>This branch doesn't seem to be in sync with the master branch, will cause
merge conflict, might be better to do a pull.
Done

***image and json files will be sent in separate email due to large file
size

On Wed, Jun 9, 2021 at 5:41 AM Subhajeet Mukherjee ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> @eelay234 <https://github.com/eelay234> Great contributions dividing the
> Expansion to dedicated better sections. 💯
>
> Couple of important things:
>
>    1. Might be better to change the directory names by removing the
>    spaces "file handling" -> "file-handling" and "conditional statements" ->
>    "conditional-statements"
>    2. Since the directory structure is changing, the
>    https://github.com/The-Programming-Foundation/tutorials/blob/master/src/data/LessonTopic.json
>    needs to be updated by replacing the Expansion and sequentially adding the
>    sections updating them with titles, subtitles and images from
>    https://unsplash.com/ feel free to chose any image you think is
>    suitable. PS make sure to change the ids of the following snippets
>    otherwise it will break.
>    3. Sequencing them as Conditional Statements -> Loops -> Functions ->
>    File Handling is suggested but if you think that swapping File Handling
>    with Functions makes more sense, feel free to sequence them that way in the
>    json file, up to you.
>    4. To add the Python Interactive Shell on the right panel, add after
>    mdx page title and at the end of the mdx file. Here's an example:
>    https://raw.githubusercontent.com/The-Programming-Foundation/tutorials/master/lessons/programming/python/hello-earth/index.mdx
>    5. This branch doesn't seem to be in sync with the master branch, will
>    cause merge conflict, might be better to do a pull.
>
> Otherwise, we're all set. 👍
> ------------------------------
>
> In lessons/programming/python/conditional statements/index.mdx
> <https://github.com/The-Programming-Foundation/tutorials/pull/37#discussion_r648097013>
> :
>
> > @@ -0,0 +1,141 @@
>
> +---
>
> +title: Conditional Statements
>
> +---
>
> +
>
> +# Conditional Statements
>
> +For some problems, we are going to take different actions depending on the conditions.
>
> +For example, take an umbrella when it's raining outside;  otherwise don't need to.
>
> +
>
> +Conditional statements are the instructions we give computers to make decisions and do something accordingly.
>
> +
>
> +There are different kinds of conditional statements.
>
> +## 1. if statement:
>
>
> *if statement* -> *If Statement*
> ------------------------------
>
> In lessons/programming/python/conditional statements/index.mdx
> <https://github.com/The-Programming-Foundation/tutorials/pull/37#discussion_r648109438>
> :
>
> > +It has one condition and takes action only when the condition is true. It does not care when the condition is
>
> +not true thus does nothing.
>
>
> *Since a condition can have multiple parameters, it might be better to
> avoid "one condition"*
>
> It has one condition and -> If a condition is true, it'll take action;
> otherwise, it'll do nothing.
> ------------------------------
>
> In lessons/programming/python/conditional statements/index.mdx
> <https://github.com/The-Programming-Foundation/tutorials/pull/37#discussion_r648112517>
> :
>
> > +---
>
> +title: Conditional Statements
>
> +---
>
> +
>
> +# Conditional Statements
>
> +For some problems, we are going to take different actions depending on the conditions.
>
> +For example, take an umbrella when it's raining outside;  otherwise don't need to.
>
> +
>
> +Conditional statements are the instructions we give computers to make decisions and do something accordingly.
>
> +
>
> +There are different kinds of conditional statements.
>
> +## 1. if statement:
>
> +It has one condition and takes action only when the condition is true. It does not care when the condition is
>
> +not true thus does nothing.
>
> +
>
> +For example,
>
>
> For example, -> *For example:*
> ------------------------------
>
> In lessons/programming/python/conditional statements/index.mdx
> <https://github.com/The-Programming-Foundation/tutorials/pull/37#discussion_r648113184>
> :
>
> > +if a number is equal to the pre-set number:
>
> +     output "You won!"
>
>
> Use ```
>
> if a number is equal to the pre-set number:
>
>      output "You won!"
>
>
> ------------------------------
>
> In lessons/programming/python/conditional statements/index.mdx
> <https://github.com/The-Programming-Foundation/tutorials/pull/37#discussion_r648114047>
> :
>
> > +For some problems, we are going to take different actions depending on the conditions.
>
> +For example, take an umbrella when it's raining outside;  otherwise don't need to.
>
> +
>
> +Conditional statements are the instructions we give computers to make decisions and do something accordingly.
>
> +
>
> +There are different kinds of conditional statements.
>
> +## 1. if statement:
>
> +It has one condition and takes action only when the condition is true. It does not care when the condition is
>
> +not true thus does nothing.
>
> +
>
> +For example,
>
> +if a number is equal to the pre-set number:
>
> +     output "You won!"
>
> +
>
> +#### Python syntax:
>
> +```
>
>
> add *Python* after ```
> ------------------------------
>
> In lessons/programming/python/conditional statements/index.mdx
> <https://github.com/The-Programming-Foundation/tutorials/pull/37#discussion_r648115037>
> :
>
> > +# Conditional Statements
>
> +For some problems, we are going to take different actions depending on the conditions.
>
> +For example, take an umbrella when it's raining outside;  otherwise don't need to.
>
> +
>
> +Conditional statements are the instructions we give computers to make decisions and do something accordingly.
>
> +
>
> +There are different kinds of  [...]

2021-06-11 22:37 UTC, eelay234 commented
Please check out unsplash.com for the images I picked. I couldn't attach
them due to the large file sizes. Sorry.

On Wed, Jun 9, 2021 at 5:41 AM Subhajeet Mukherjee ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> @eelay234 <https://github.com/eelay234> Great contributions dividing the
> Expansion to dedicated better sections. 💯
>
> Couple of important things:
>
>    1. Might be better to change the directory names by removing the
>    spaces "file handling" -> "file-handling" and "conditional statements" ->
>    "conditional-statements"
>    2. Since the directory structure is changing, the
>    https://github.com/The-Programming-Foundation/tutorials/blob/master/src/data/LessonTopic.json
>    needs to be updated by replacing the Expansion and sequentially adding the
>    sections updating them with titles, subtitles and images from
>    https://unsplash.com/ feel free to chose any image you think is
>    suitable. PS make sure to change the ids of the following snippets
>    otherwise it will break.
>    3. Sequencing them as Conditional Statements -> Loops -> Functions ->
>    File Handling is suggested but if you think that swapping File Handling
>    with Functions makes more sense, feel free to sequence them that way in the
>    json file, up to you.
>    4. To add the Python Interactive Shell on the right panel, add after
>    mdx page title and at the end of the mdx file. Here's an example:
>    https://raw.githubusercontent.com/The-Programming-Foundation/tutorials/master/lessons/programming/python/hello-earth/index.mdx
>    5. This branch doesn't seem to be in sync with the master branch, will
>    cause merge conflict, might be better to do a pull.
>
> Otherwise, we're all set. 👍
> ------------------------------
>
> In lessons/programming/python/conditional statements/index.mdx
> <https://github.com/The-Programming-Foundation/tutorials/pull/37#discussion_r648097013>
> :
>
> > @@ -0,0 +1,141 @@
>
> +---
>
> +title: Conditional Statements
>
> +---
>
> +
>
> +# Conditional Statements
>
> +For some problems, we are going to take different actions depending on the conditions.
>
> +For example, take an umbrella when it's raining outside;  otherwise don't need to.
>
> +
>
> +Conditional statements are the instructions we give computers to make decisions and do something accordingly.
>
> +
>
> +There are different kinds of conditional statements.
>
> +## 1. if statement:
>
>
> *if statement* -> *If Statement*
> ------------------------------
>
> In lessons/programming/python/conditional statements/index.mdx
> <https://github.com/The-Programming-Foundation/tutorials/pull/37#discussion_r648109438>
> :
>
> > +It has one condition and takes action only when the condition is true. It does not care when the condition is
>
> +not true thus does nothing.
>
>
> *Since a condition can have multiple parameters, it might be better to
> avoid "one condition"*
>
> It has one condition and -> If a condition is true, it'll take action;
> otherwise, it'll do nothing.
> ------------------------------
>
> In lessons/programming/python/conditional statements/index.mdx
> <https://github.com/The-Programming-Foundation/tutorials/pull/37#discussion_r648112517>
> :
>
> > +---
>
> +title: Conditional Statements
>
> +---
>
> +
>
> +# Conditional Statements
>
> +For some problems, we are going to take different actions depending on the conditions.
>
> +For example, take an umbrella when it's raining outside;  otherwise don't need to.
>
> +
>
> +Conditional statements are the instructions we give computers to make decisions and do something accordingly.
>
> +
>
> +There are different kinds of conditional statements.
>
> +## 1. if statement:
>
> +It has one condition and takes action only when the condition is true. It does not care when the condition is
>
> +not true thus does nothing.
>
> +
>
> +For example,
>
>
> For example, -> *For example:*
> ------------------------------
>
> In lessons/programming/python/conditional statements/index.mdx
> <https://github.com/The-Programming-Foundation/tutorials/pull/37#discussion_r648113184>
> :
>
> > +if a number is equal to the pre-set number:
>
> +     output "You won!"
>
>
> Use ```
>
> if a number is equal to the pre-set number:
>
>      output "You won!"
>
>
> ------------------------------
>
> In lessons/programming/python/conditional statements/index.mdx
> <https://github.com/The-Programming-Foundation/tutorials/pull/37#discussion_r648114047>
> :
>
> > +For some problems, we are going to take different actions depending on the conditions.
>
> +For example, take an umbrella when it's raining outside;  otherwise don't need to.
>
> +
>
> +Conditional statements are the instructions we give computers to make decisions and do something accordingly.
>
> +
>
> +There are different kinds of conditional statements.
>
> +## 1. if statement:
>
> +It has one condition and takes action only when the condition is true. It does not care when the condition is
>
> +not true thus does nothing.
>
> +
>
> +For example,
>
> +if a number is equal to the pre-set number:
>
> +     output "You won!"
>
> +
>
> +#### Python syntax:
>
> +```
>
>
> add *Python* after ```
> ------------------------------
>
> In lessons/programming/python/conditional statements/index.mdx
> <https://github.com/The-Programming-Foundation/tutorials/pull/37#discussion_r648115037>
> :
>
> > +# Conditional Statements
>
> +For some problems, we are going to take different actions depending on the conditions.
>
> +For example, take an umbrella when it's raining outside;  otherwise don't need to.
>
> +
>
> +Conditional statements are the instructions we give computers to make decisions and do something accordingly.
>
> +
>
> +There are different kinds of conditional statements.
>
> +## 1. if statement:
>
> +It has one condition and takes action only when the condition is true. It does not care when the condition is
>
> +not true thus does nothing.
>
> +
>
> +For example,
>
> +if a number is equal to the pre-set number:
>
> +     output "You won!"
>
> +
>
> +#### Python syntax:
>
>
> "###"
> ------------------------------
>
> In lessons/programming/python/conditional statements/index.mdx
> <https://github.com/The-Programming-Foundation/tutorials/pull/37#discussion_r648127474>
> :
>
> > +     output "You won!"
>
> +
>
> +#### Python syntax:
>
> +```
>
> +if condition:
>
> +    do something
>
> +```
>
> +### Python implementation:
>
> +```Python
>
> +winning_number = 65
>
> +num = int(input("Pick a lucky number between 1 and 100: "))
>
> +
>
> +if num == winning_number:
>
> +    print("You won!")
>
> +```
>
> +Output:
>
>
> In bold
> ------------------------------
>
> In lessons/programming/python/conditional statements/index.mdx
> <https://github.com/The-Programming-Foundation/tutorials/pull/37#discussion_r648131319>
> :
>
> > +winning_number = 65
>
> +num = int(input("Pick a lucky number between 1 and 100: "))
>
> +
>
> +if num == winning_number:
>
> +    print("You won!")
>
>
> Might be better to add comments:
>
>
> *Assigning a number to the winning_number variable Assigning the user int
> input to the num variable or Asking the user to type in a lucky integer
> number*
> ------------------------------
>
> In lessons/programming/python/conditional statements/index.mdx
> <https://github.com/The-Programming-Foundation/tutorials/pull/37#discussion_r648132598>
> :
>
> > +```
>
> +### Python implementation:
>
> +```Python
>
> +winning_number = 65
>
> +num = int(input("Pick a lucky number between 1 and 100: "))
>
> +
>
> +if num == winning_number:
>
> +    print("You won!")
>
> +```
>
> +Output:
>
> +```
>
> +Pick a lucky number between 1 and 100: 65
>
> +You won!
>
> +```
>
> +
>
> +## 2. if-else statement:
>
>
> if-else statement: -> *If-Else Statement*
> ------------------------------
>
> In lessons/programming/python/conditional statements/index.mdx
> <https://github.com/The-Programming-Foundation/tutorials/pull/37#discussion_r648137919>
> :
>
> > +###  [...]

2021-06-12 08:37 UTC, bootkernel requested changes
Hi @eelay234 Thanks for making those changes, I've requested some minor further changes. In the file-handling's index.mdx file, it seemed like the "<" and ">" in **Writing a file** section were causing errors and the page wasn't loading. Replacing the < and > with " and " fixes the issues.

And don't worry about the images and the json file, I'll take care of them.

2021-06-12 08:37 UTC, bootkernel commented on lessons/programming/python/conditional-statements/index.mdx
> +# The Python power operator ** raises the left number to the power of the right numer
Typo:
of the right numer -> **number**

2021-06-12 08:37 UTC, bootkernel commented on lessons/programming/python/conditional-statements/index.mdx
> +Python probvides a shorthand method like the ternary operator of C languge for writing if-else statement in one line.
Typo:

Python probvides -> **provides** 

ternary operator of C languge -> **language**

statement -> **statements**

2021-06-12 08:37 UTC, bootkernel commented on lessons/programming/python/file-handling/index.mdx
> +**writelines(<a list of strings is specified>)**: write multiple strings, each string as a line, into a file.<br />
Okay @eelay234 so for some reason, using "<" and ">", was causing issues in the mdx file, it was showing errors and the page wasn't loading. Replacing < and > with " and " works.

~~<~~ a string is specified ~~>~~ -> (**"**a string is specified**"**)

~~<~~ a list of strings is specified ~~>~~ -> (**"**a list of strings ~~is~~ -> **are**  specified**"**)

2021-06-12 08:37 UTC, bootkernel commented on lessons/programming/python/file-handling/index.mdx
> +The built-in **open()** function opens and gaining access to a file. It accesses a file by the specified filename (in the current directory) or a path to that file.
The built-in **open()** function opens and ~~gaining~~ -> **gains** access to a file.

2021-06-12 08:37 UTC, bootkernel commented on lessons/programming/python/file-handling/index.mdx
> +#### The content in shopping_memo_txt after execution:
The content in shopping_memo_txt ->  **shopping_memo.txt** after execution

2021-06-12 08:37 UTC, bootkernel commented on lessons/programming/python/functions/index.mdx
> +Built-in functions are pre-defined in and a part of Python languagne such as print(), range(), and type().
Typo:
pre-defined ~~in~~ and ~~a~~ part of the Python ~~languagne~~ -> **language**

2021-06-15 06:14 UTC, bootkernel approved these changes
@eelay234 I'm approving the changes but before I merge, @hcs847 will make some changes in the file structure, add image links and update the documentation for new content contributors.

2021-06-15 15:58 UTC, merged